#!/bin/bash


inteval=$1; echo "=)"
file1="f1"
file2="f2"
command=""

count=1
for arg in "$@"; do
    if [ count != 1 ] then

        command=

    fi 

done



touch $file1
touch $file2


while [ 1 ]; do
    echo "gg"
    sleep $interval 
    

done
